# -*- coding: utf-8 -*-
"""tel_bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PBo9Wfzba1zr561nJ8Ik_0cEP_5KheAe
"""

!pip install pyTelegramBotAPI
!pip install gtts
!pip install telegram
!pip install git+https://github.com/eternnoir/pyTelegramBotAPI.git
!pip install qrcode

!pip install khayyam
!pip install jdatetime

import telebot 
import random
import jdatetime
import gtts
#from telebot.types import Message
from gtts import gTTS
#from telegram import ReplyKeyboardMarkup
from datetime import datetime , date
from khayyam import jalali_date , jalali_datetime 
bot = telebot.TeleBot("5843752190:AAGme0OZWXRxcmWja5L2ksGcihPmPdaD238"  )
from telebot import types
import qrcode

@bot.message_handler(commands=['help']) 
def help(message):
    my_keyboard= telebot.types.ReplyKeyboardMarkup(row_width=3)
    key1 = telebot.types.KeyboardButton("/game")
    key2 = telebot.types.KeyboardButton("/age")
    key3 = telebot.types.KeyboardButton("/voice")
    key4 = telebot.types.KeyboardButton("/max")
    key5 = telebot.types.KeyboardButton("/argmax")
    key6 = telebot.types.KeyboardButton("/qrcode")
    key7 = types.KeyboardButton("/help")
    my_keyboard.row(key1, key2 , key3)
    my_keyboard.row(key4, key5, key6)
    my_keyboard.row(key7)
    bot.send_message(message.chat.id ,"Choose one of the below keys :" , reply_markup=my_keyboard)




@bot.message_handler(commands=['start']) #decorator 
def send_welcome(message):
  bot.send_message(message.chat.id , " Hi " + message.from_user.first_name + "\nWelcome to Pybot")
  help(message)





global today_time
global user_birthday
@bot.message_handler(commands=['age'])
def Age_calculator(message):   
    initial_message = bot.send_message(message.chat.id, "enter your birthday in this format yy/mm/dd : " )
    bot.register_next_step_handler(initial_message , age_calc)
def age_calc(message):
    today_time = jdatetime.date.today()
    user_birthday = message.text
    user_birthday = user_birthday.split("/")
    today_time = jdatetime.date.today()
    today_time = str(today_time)
    print(today_time)
    today_time = today_time.split("-")
    year , month , day = user_birthday
    age_year = int(today_time[0]) - int(user_birthday[0])
    age_month = int(today_time[1]) - int(user_birthday[1])
    age_day = int(today_time[2]) - int(user_birthday[2])
    if today_time[1] < user_birthday[1] :
        age_year -= 1 
        age_month += 12
    if today_time[2] < user_birthday[2] :
        age_day += 30
    age_output = "your age is : "+ str(age_year) + " year and " +str(age_month) + " month and " + str(age_day) + " days"
    bot.send_message(message.chat.id ,  age_output)




@bot.message_handler(commands=['voice'])
def text_to_voice(message):
    initial_message = bot.send_message(message.chat.id, "enter the text you want to convert to voice : " )
    bot.register_next_step_handler(initial_message , txt2voice)
def txt2voice(message):
    text = message.text
    voice = gtts.gTTS( text , lang = "en" , slow = False )
    voice.save("/content/drive/MyDrive/Colab Notebooks/text_to_voice.mp3")
    r_voice = open("/content/drive/MyDrive/Colab Notebooks/text_to_voice.mp3" ,"rb")
    bot.send_voice(message.chat.id , r_voice)




@bot.message_handler(commands=['max'])
def print_max_number(message):
    initial_message = bot.send_message(message.chat.id, "Enter a String Of Numbers,\nSeparate Them With Comma,\nTo Define Maximum : " )
    bot.register_next_step_handler(initial_message , max_finder)
def max_finder(message):
    string = message.text
    array = string.split("," or " " or " ," or ", ")
    for i in range(len(array)):
        array[i] = int(array[i])
    max=array[0]    
    for i in range(1,len(array)-1) :
        if array[i] > max :
            max=array[i]   
    bot.send_message(message.chat.id , max)




@bot.message_handler(commands=['argmax'])
def return_max_index(message):
    initial_message = bot.send_message(message.chat.id, "Enter a String Of Numbers,\nSeparate Them With Comma,\nTo Define Maximum number index: " )
    bot.register_next_step_handler(initial_message , max_index)
def max_index(message):
    string = message.text
    array = string.split("," or " " or " ," or ", ")
    for i in range(len(array)):
        array[i] = int(array[i])
    max=array[0]    
    for i in range(len(array)-1) :
        if array[i] > max :
            max=array[i]
            index = i   
    argmax = "maximum number is "  + str(max) + "\nit's index is : "+ str(index)  
    bot.send_message(message.chat.id , argmax)




@bot.message_handler(commands=['qrcode'])
def Qrcode_generator(message):   
    initial_message = bot.send_message(message.chat.id, "Enter Anything to convert it to qrcode : " )
    bot.register_next_step_handler(initial_message , Qrcode)
def Qrcode(message):
    q_text = message.text
    qr = qrcode.make(q_text)
    qr.save("/content/drive/MyDrive/Colab Notebooks/Qrcode1.png")
    qr_image = open("/content/drive/MyDrive/Colab Notebooks/Qrcode1.png" , "rb")
    bot.send_photo(message.chat.id , qr_image)





@bot.message_handler(commands=['game'])
def Guess_number_game(message):
    global RAND
    RAND = random.randint(0 , 50)
    bot.send_message(message.chat.id, "guess a number between 0 and 50 : " )
@bot.message_handler(func=lambda m: True)
def echo_all(message):
    new_keyboard= telebot.types.ReplyKeyboardMarkup(row_width=1)
    new_game_key = telebot.types.KeyboardButton("new game")
    new_keyboard.add(new_game_key)
    new_keyboard.row(new_game_key)
    if RAND > int(message.text) :
        bot.send_message(message.chat.id , "GO UP")
    elif RAND < int(message.text) :
        bot.send_message(message.chat.id , "GO Down") 
    elif RAND == int(message.text) :
        bot.send_message(message.chat.id , "YOU WON")

from google.colab import drive
drive.mount('/content/drive')

bot.infinity_polling()